//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MebelkiModel.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MebelkiModel.Resource.res", typeof(res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GBP.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color.
        /// </summary>
        internal static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height1.
        /// </summary>
        internal static string Height1 {
            get {
                return ResourceManager.GetString("Height1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height2.
        /// </summary>
        internal static string Height2 {
            get {
                return ResourceManager.GetString("Height2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Client.
        /// </summary>
        internal static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Furniture.
        /// </summary>
        internal static string NewFurniture {
            get {
                return ResourceManager.GetString("NewFurniture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board can have only one vaneer per side of the board..
        /// </summary>
        internal static string OnePerSideVaneerException {
            get {
                return ResourceManager.GetString("OnePerSideVaneerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board can have maximum 4 vaneers..
        /// </summary>
        internal static string OverFourVaneersException {
            get {
                return ResourceManager.GetString("OverFourVaneersException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width1.
        /// </summary>
        internal static string Width1 {
            get {
                return ResourceManager.GetString("Width1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width2.
        /// </summary>
        internal static string Width2 {
            get {
                return ResourceManager.GetString("Width2", resourceCulture);
            }
        }
    }
}
